services:
  telegram-proxy:
      image: telegrammessenger/proxy:latest
      container_name: tg-proxy
      ports:
        - "443:443"
      volumes:
        - "proxy-config:/data"
      restart: unless-stopped
      environment:
        - SECRET=${SECRET}
        - SECRET_COUNT=${SECRET_COUNT}
        - WORKERS=${WORKERS}
  tg-proxy-watchtower:
    image: v2tec/watchtower
    container_name: tg-proxy-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: telegrammessenger/proxy:latest
    restart: unless-stopped
volumes:
  proxy-config:

