services:

  socks5:
    restart: always
    image: serjs/go-socks5-proxy
    environment:
      - PROXY_USER=ultrageopro
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - PROXY_PORT=443
    ports:
      - "443:443"